image: node:latest

before_script:
  - npm install

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .next/cache/

pages:
  script:
    - npm run build
    - mv out/* public
    - rm -rf out
  artifacts:
    paths:
      - public
  only:
    - main
