image: node:latest

before_script:
  - npm install

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

pages:
  script:
    - npm run build
    - mv dist/* public
    - rm -rf dist
  artifacts:
    paths:
      - public
  only:
    - main
